packaging_format = 2

id = "akkoma"
name = "Akkoma"
description.en = "Federated social networking server built on ActivityPub open protocol"
description.fr = "Serveur de réseautage social fédéré basé sur le protocole ouvert ActivityPub"

version = "3.10.4~ynh3"

maintainers = ["Lapineige"]

[upstream]
license = "AGPL-3.0-only"
website = "https://akkoma.social/"
demo = "https://otp.akkoma.dev"
admindoc = "https://docs.akkoma.dev/stable/"
code = "https://akkoma.dev/AkkomaGang/akkoma/"

[integration]
yunohost = ">= 12.0"
architectures = ["amd64"] # FIXME HELPWANTED "arm64"
multi_instance = false
ldap = false
sso = false
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "password"

    [install.instance_name]
    ask.en = "Choose a name for your Akkoma instance"
    ask.fr = "Choisissez un nom pour votre instance Akkoma"
    type = "string"
    example = "My_akkoma"
    default = "My_akkoma"

    [install.registration]
    ask.en = "Should registration be open to users who do not have a YunoHost account on the system?"
    ask.fr = "L'inscription doit-elle être ouverte aux utilisateurs qui n'ont pas de compte YunoHost sur le système ?"
    type = "boolean"
    default = false

    [install.cache]
    ask.en = "Enable media-cache for your instance: downloaded media won't be downloaded twice, at the price of storage capacity."
    ask.fr = "Activer le cache média pour votre instance : les médias téléchargés le seront pas deux fois, au prix d'un plus grande utilisation de l'espace de stockage."
    type = "boolean"
    default = true

    [install.size]
    ask.en = "Select the media-cache size (in GB). If you did not enabled media-cache in above option then this option will have no effect. This can be tweaked afterwards."
    ask.fr = "Sélectionner la taille du cache média (en Go). Si vous n'avez pas activé le cache média ci-dessus, cette option n'aura aucun effet. Cela peut être ajusté après-coup."
    type = "select"
    choices = ["1g", "2g", "5g", "10g", "20g", "40g", "60g", "100g", "150g"]
    default = "5g"

[resources]

    [resources.sources.main]
    url = "https://akkoma-updates.s3-website.fr-par.scw.cloud/stable/akkoma-amd64.zip"
    sha256 = "146b148be0e71482e7614246b8a0c563a5c45ed6581e20f70035b3e3a2377ba2"
    # autoupdate.strategy = "latest_github_release" # How to implement this ?
    # autoupdate.asset = ".*\\.zip"
    
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095 # FIXME

    [resources.apt]
    packages = "curl, unzip, libncurses5, postgresql, postgresql-contrib, imagemagick, ffmpeg, exiftool, libimage-exiftool-perl"

    [resources.database]
    type = "postgresql"
