#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_package_version
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading settings..." --weight=1

#REMOVEME? app=$YNH_APP_INSTANCE_NAME

#REMOVEME? domain=$(ynh_app_setting_get --app=$app --key=domain)
#REMOVEME? path=$(ynh_app_setting_get --app=$app --key=path)
#REMOVEME? admin=$(ynh_app_setting_get --app=$app --key=admin)
#REMOVEME? #REMOVEME? install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
#REMOVEME? db_name=$(ynh_app_setting_get --app=$app --key=db_name)
#REMOVEME? db_user=$db_name
#REMOVEME? db_pwd=$(ynh_app_setting_get --app=$app --key=psqlpwd)
#REMOVEME? admin_email=$(ynh_app_setting_get --app=$app --key=admin_email)
#REMOVEME? random_key=$(ynh_app_setting_get --app=$app --key=random_key)
#REMOVEME? name=$(ynh_app_setting_get --app=$app --key=name)
#REMOVEME? port=$(ynh_app_setting_get --app=$app --key=port)
#REMOVEME? cache=$(ynh_app_setting_get --app=$app --key=cache)
#REMOVEME? size=$(ynh_app_setting_get --app=$app --key=size)
#REMOVEME? registration=$(ynh_app_setting_get --app=$app --key=registration)

#=================================================
# CHECK VERSION
#=================================================
ynh_script_progression --message="Checking version..." --weight=1

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# CHECK VERSION NUMBER
#=================================================
ynh_script_progression --message="Checking version number..." --weight=1

if [ ${PACKAGE_CHECK_EXEC:-0} -eq 1 ]; then
  sleep 60
fi
abort_if_up_to_date
# previous function is what defines 'version', more precisely the 'previous version'
previous_version="${version}"

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="stop" --log_path=systemd --line_match="Stopped $app"

if ynh_version_gt "${previous_version}" "1.1.1~ynh1"  ; then
	pkill -u $app || true
fi

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1


# Close a port
if yunohost firewall list | grep -q "\- $port$"
then
	ynh_script_progression --message="Closing port $port..."
	ynh_exec_warn_less yunohost firewall disallow TCP $port
fi

# Remove old repository
ynh_secure_remove --file="/etc/apt/sources.list.d/erlang-solutions.list"
apt-key del A14F4FCA

# Switch to $install_dir/live
if [ ! -d "$install_dir/live" ]; then
	mv $install_dir/$app $install_dir/live
fi

#=================================================
# UPGRADE TO OTP RELEASE
#=================================================

config="/etc/$app/config.exs"
if ynh_version_gt "1.1.1~ynh1" "${previous_version}" ; then
	ynh_script_progression --message="Upgrading to OTP release..." --weight=1

	# Create app folders
	mkdir -p "$data_dir/"
	mkdir -p "$data_dir/uploads/"
	mkdir -p "$data_dir/static/"
	mkdir -p "$data_dir/static/emoji/"

	# Give permission to the data_dir
	chown -R "$app":"$app" "$data_dir"

	rsync -a "$install_dir/live/uploads/" "$data_dir/uploads/"
	if [ -d "$install_dir/live/instance/static/" ]; then
		rsync -a "$install_dir/live/instance/static/" "$data_dir/static/"
	fi

	rsync -a "$install_dir/live/priv/static/emoji/" "$data_dir/static/emoji/"

	mkdir -p /etc/$app
	chown -R $app /etc/$app
	mv $install_dir/live/config/prod.secret.exs $config
	ynh_replace_string --match_string="use Mix.Config" --replace_string="import Config" --target_file="$config"
	echo "config :akkoma, :instance, static_dir: \"/home/yunohost.app/$app/static\"" >> $config
	echo "config :akkoma, akkoma.Uploaders.Local, uploads: \"/home/yunohost.app/$app/uploads\"" >> $config

	ynh_backup_if_checksum_is_different --file="$config"

	ynh_secure_remove --file="$install_dir/live"
fi

if ynh_version_gt "2.0.5~ynh1" "${previous_version}" ; then
	cat "../conf/ldap.exs" >> "$config"
	ynh_replace_string --match_string="config :akkoma, configurable_from_database: false" --replace_string="config :akkoma, configurable_from_database: true" --target_file="$config"
fi

if ynh_version_gt "2.4.4~ynh2" "${previous_version}"; then
	registration_bool_value=`(($registration)) && echo "true" || echo "false"`
	ynh_replace_string --match_string='registrations_open: true' --replace_string="registrations_open: $registration_bool_value" --target_file="$config"
fi

# Add frontend switcher if needed

if grep -zP  'config :pleroma, :frontends,\n\K  pickable' $config # This syntax takes the new line into account # This is not resilient to any spacing change, to be refined
then
    ynh_script_progression --message="Frontend switcher config already existing, nothing to do about it." --weight=0
else
    ynh_script_progression --message="Adding frontend switcher config." --weight=0
    cat "../conf/frontend_switcher.exs" >> "$config"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=1

	ynh_secure_remove --file="$install_dir/live"
	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir/live" --source_id=$YNH_ARCH
fi

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
#REMOVEME? ynh_script_progression --message="Upgrading dependencies..." --weight=1

#REMOVEME? ynh_exec_warn_less ynh_install_app_dependencies $pkg_dependencies

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=1

if [ $cache -eq 1 ]
then
	ynh_add_config --template="../conf/cache.conf" --destination="/etc/nginx/conf.d/$app-cache.conf"

	cat ../conf/media.conf >> ../conf/nginx.conf
fi

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC UPGRADE
#=================================================
# MAKE UPGRADE
#=================================================
ynh_script_progression --message="Making upgrade..." --weight=1

pushd $install_dir/live
	ynh_exec_warn_less ynh_exec_as $app -s $SHELL -lc "$install_dir/live/bin/pleroma_ctl migrate"
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating a configuration file..." --weight=1

config="/etc/$app/config.exs"

ynh_backup_if_checksum_is_different --file="$config"

chmod 400 "$config"
chown $app:$app "$config"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Upgrading systemd configuration..." --weight=1

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# GENERIC FINALIZATION
#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1

yunohost service add $app --description="$app daemon for akkoma"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path=systemd --line_match="Access akkoma.Web.Endpoint"

#=================================================
# INSTALL BASIC FRONTENDS (Upgrade them)
#=================================================
#### Fontends need Akkoma to be already running, so they are installed at the very end

# Pleroma Front-End
ynh_script_progression --message="Upgrading Pleroma FrontEnd..." --weight=1
ynh_exec_warn_less ynh_exec_as $app -s $SHELL -lc "$install_dir/live/bin/pleroma_ctl frontend install pleroma-fe --ref stable"

# Admin Front-End
ynh_script_progression --message="Upgrading Admin FrontEnd..." --weight=1
ynh_exec_warn_less ynh_exec_as $app -s $SHELL -lc "$install_dir/live/bin/pleroma_ctl frontend install admin-fe --ref stable"

#=================================================
# INSTALL MANGANE FRONTEND (Upgrade it)
#=================================================
# Mangane alternative Front-End will be built in, ready to enable
ynh_script_progression --message="Upgrading Mangane FrontEnd..." --weight=1
ynh_exec_warn_less ynh_exec_as $app -s $SHELL -lc "$install_dir/live/bin/pleroma_ctl frontend install mangane --ref dist --build-url https://github.com/BDX-town/Mangane/releases/latest/download/static.zip"
# Not activated, users need to change the "primary" frontend in the admin UI (use 'mangane' and 'dist').

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading NGINX web server..." --weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
